ALTER TABLE "DIRECCION_PERSONA" DROP CONSTRAINT "fk_DIRECCION_PERSONA" CASCADE;
ALTER TABLE "DIRECCION_PERSONA" DROP CONSTRAINT "fk_DIRECCION_PERSONA_1" CASCADE;
ALTER TABLE "DEPARTAMENTO" DROP CONSTRAINT "fk_DEPARTAMENTO" CASCADE;
ALTER TABLE "MUNICIPIO" DROP CONSTRAINT "fk_MUNICIPIO" CASCADE;
ALTER TABLE "DIRECCION" DROP CONSTRAINT "fk_DIRECCION" CASCADE;
ALTER TABLE "DIRECCION" DROP CONSTRAINT "fk_DIRECCION_1" CASCADE;
ALTER TABLE "TELEFONO_PERSONA" DROP CONSTRAINT "fk_TELEFONO_PERSONA" CASCADE;
ALTER TABLE "TELEFONO_PERSONA" DROP CONSTRAINT "fk_TELEFONO_PERSONA_1" CASCADE;
ALTER TABLE "DOCUMENTO" DROP CONSTRAINT "fk_DOCUMENTO" CASCADE;
ALTER TABLE "DOCUMENTO_PERSONA" DROP CONSTRAINT "fk_DOCUMENTO_PERSONA" CASCADE;
ALTER TABLE "DOCUMENTO_PERSONA" DROP CONSTRAINT "fk_DOCUMENTO_PERSONA_1" CASCADE;
ALTER TABLE "TELEFONO" DROP CONSTRAINT "fk_TELEFONO" CASCADE;
ALTER TABLE "TELEFONO" DROP CONSTRAINT "fk_TELEFONO_1" CASCADE;
ALTER TABLE "CLIENTE" DROP CONSTRAINT "fk_CLIENTE" CASCADE;
ALTER TABLE "PAGO" DROP CONSTRAINT "fk_PAGO" CASCADE;
ALTER TABLE "CLIENTE" DROP CONSTRAINT "fk_CLIENTE_1" CASCADE;
ALTER TABLE "PERSONA" DROP CONSTRAINT "fk_PERSONA" CASCADE;
ALTER TABLE "PAGO" DROP CONSTRAINT "fk_PAGO_1" CASCADE;

ALTER TABLE "PERSONA" DROP CONSTRAINT "CHECK_ID_PERSONA" CASCADE;

DROP TABLE "PERSONA" CASCADE CONSTRAINTS;
DROP TABLE "DIRECCION_PERSONA" CASCADE CONSTRAINTS;
DROP TABLE "DIRECCION" CASCADE CONSTRAINTS;
DROP TABLE "COLONIA" CASCADE CONSTRAINTS;
DROP TABLE "DEPARTAMENTO" CASCADE CONSTRAINTS;
DROP TABLE "MUNICIPIO" CASCADE CONSTRAINTS;
DROP TABLE "PAIS" CASCADE CONSTRAINTS;
DROP TABLE "TELEFONO" CASCADE CONSTRAINTS;
DROP TABLE "TELEFONO_PERSONA" CASCADE CONSTRAINTS;
DROP TABLE "DOCUMENTO_PERSONA" CASCADE CONSTRAINTS;
DROP TABLE "TIPO_DOCUMENTO" CASCADE CONSTRAINTS;
DROP TABLE "DOCUMENTO" CASCADE CONSTRAINTS;
DROP TABLE "COMPANIA_TELEFONO" CASCADE CONSTRAINTS;
DROP TABLE "TIPO_TELEFONO" CASCADE CONSTRAINTS;
DROP TABLE "CLIENTE" CASCADE CONSTRAINTS;
DROP TABLE "ESTADO" CASCADE CONSTRAINTS;
DROP TABLE "PAGO" CASCADE CONSTRAINTS;
DROP TABLE "TIPO_PAGO" CASCADE CONSTRAINTS;

CREATE TABLE "PERSONA" (
"ID_PERSONA" NUMBER NOT NULL,
"PRIMER_NOMBRE" VARCHAR2(30) NOT NULL,
"SEGUNDO_NOMBRE" VARCHAR2(30) NULL,
"PRIMER_APELLIDO" VARCHAR2(30) NOT NULL,
"SEGUNDO_APELLIDO" VARCHAR2(30) NULL,
"APELLIDO_CASADA" VARCHAR2(30) NULL,
"FECHA_NACIMIENTO" DATE NOT NULL,
"GENERO" CHAR(1 ) NOT NULL,
"FECHA_REGISTRO" DATE NOT NULL,
"USUARIO_REGISTRO" NUMBER NOT NULL,
"ID_ESTADO" NUMBER NULL,
PRIMARY KEY ("ID_PERSONA") 
)
NOCOMPRESS 
NOPARALLEL ;
ALTER TABLE "PERSONA" ADD CONSTRAINT "CHECK_ID_PERSONA" CHECK (ID_PERSONA IS NOT NULL) ENABLE;

CREATE TABLE "DIRECCION_PERSONA" (
"ID_DIRECCION" NUMBER DEFAULT   NOT NULL,
"ID_PERSONA" NUMBER NOT NULL
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "DIRECCION" (
"ID_DIRECCION" NUMBER NOT NULL,
"ID_COLONIA" NUMBER NULL,
"ID_ZONA" NUMBER NULL,
"FECHA_REGISTRO" DATE NOT NULL,
"CALLE_AVENIDA" VARCHAR2(30) NULL,
"ID_MUNICIPIO" NUMBER NOT NULL,
PRIMARY KEY ("ID_DIRECCION") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "COLONIA" (
"ID_COLONIA" NUMBER NOT NULL,
"ID_MUNICIPIO" NUMBER NOT NULL,
"COLONIA" VARCHAR2(30) NOT NULL,
"CALLE" VARCHAR2(30) NULL,
"EDIFICIO" VARCHAR2(30) NULL,
PRIMARY KEY ("ID_COLONIA") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "DEPARTAMENTO" (
"ID_DEPARTAMENTO" NUMBER NOT NULL,
"ID_PAIS" NUMBER NOT NULL,
"DEPARTAMENTO" VARCHAR2(50) NOT NULL,
PRIMARY KEY ("ID_DEPARTAMENTO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "MUNICIPIO" (
"ID_MUNICIPIO" NUMBER NOT NULL,
"ID_DEPARTAMENTO" NUMBER NOT NULL,
"MUNICIPIO" VARCHAR2(30) NOT NULL,
PRIMARY KEY ("ID_MUNICIPIO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "PAIS" (
"ID_PAIS" NUMBER NOT NULL,
"PAIS" VARCHAR2(30) NOT NULL,
PRIMARY KEY ("ID_PAIS") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "TELEFONO" (
"ID_TELEFONO" NUMBER NOT NULL,
"ID_TIPO_TELEFONO" NUMBER NULL,
"ID_COMPANIA" NUMBER NULL,
"TELEFONO" NUMBER(15,0) NULL,
PRIMARY KEY ("ID_TELEFONO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "TELEFONO_PERSONA" (
"ID_TELEFONO" NUMBER NOT NULL,
"ID_PERSONA" NUMBER NOT NULL
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "DOCUMENTO_PERSONA" (
"ID_DOCUMENTO" NUMBER NOT NULL,
"ID_PERSONA" NUMBER NOT NULL
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "TIPO_DOCUMENTO" (
"ID_TIPO_DOCUMENTO" NUMBER NOT NULL,
"TIPO_DOCUMENTO" VARCHAR2(30) NOT NULL,
PRIMARY KEY ("ID_TIPO_DOCUMENTO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "DOCUMENTO" (
"ID_DOCUMENTO" NUMBER NOT NULL,
"DOCUMENTO" VARCHAR2(30) NOT NULL,
"ID_TIPO_DOCUMENTO" NUMBER NOT NULL,
PRIMARY KEY ("ID_DOCUMENTO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "COMPANIA_TELEFONO" (
"ID_COMPANIA" NUMBER NOT NULL,
"COMPANIA" VARCHAR2(20) NOT NULL,
PRIMARY KEY ("ID_COMPANIA") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "TIPO_TELEFONO" (
"ID_TIPO_TELEFONO" NUMBER NOT NULL,
"TIPO_TELEFONO" VARCHAR2(50) NOT NULL,
PRIMARY KEY ("ID_TIPO_TELEFONO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "CLIENTE" (
"ID_CLIENTE" NUMBER NOT NULL,
"ID_PERSONA" NUMBER NOT NULL,
"CODIGO" VARCHAR2(30) NOT NULL,
"ID_ESTADO" VARCHAR2(255) NULL,
PRIMARY KEY ("ID_CLIENTE") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "ESTADO" (
"ID_ESTADO" NUMBER NOT NULL,
"ESTADO" VARCHAR2(30) NOT NULL,
PRIMARY KEY ("ID_ESTADO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "PAGO" (
"ID_PAGO" NUMBER NOT NULL,
"ID_CLIENTE" NUMBER NOT NULL,
"ID_TIPO_PAGO" NUMBER NOT NULL,
"MONTO" NUMBER(10,0) NOT NULL,
"FECHA_REGISTRO" DATE NOT NULL,
"USUARIO_REGISTRO" NUMBER NOT NULL,
"DOCUMENTO_PAGO" VARCHAR2(30) NOT NULL,
PRIMARY KEY ("ID_PAGO") 
)
NOCOMPRESS 
NOPARALLEL ;
CREATE TABLE "TIPO_PAGO" (
"ID_TIPO_PAGO" NUMBER NOT NULL,
"TIPO_PAGO" VARCHAR2(30) NOT NULL,
PRIMARY KEY ("ID_TIPO_PAGO") 
)
NOCOMPRESS 
NOPARALLEL ;

ALTER TABLE "DIRECCION_PERSONA" ADD CONSTRAINT "fk_DIRECCION_PERSONA" FOREIGN KEY ("ID_DIRECCION") REFERENCES "DIRECCION" ("ID_DIRECCION") ON DELETE CASCADE;
ALTER TABLE "DIRECCION_PERSONA" ADD CONSTRAINT "fk_DIRECCION_PERSONA_1" FOREIGN KEY ("ID_PERSONA") REFERENCES "PERSONA" ("ID_PERSONA") ON DELETE CASCADE;
ALTER TABLE "DEPARTAMENTO" ADD CONSTRAINT "fk_DEPARTAMENTO" FOREIGN KEY ("ID_PAIS") REFERENCES "PAIS" ("ID_PAIS") ON DELETE CASCADE;
ALTER TABLE "MUNICIPIO" ADD CONSTRAINT "fk_MUNICIPIO" FOREIGN KEY ("ID_DEPARTAMENTO") REFERENCES "DEPARTAMENTO" ("ID_DEPARTAMENTO") ON DELETE CASCADE;
ALTER TABLE "DIRECCION" ADD CONSTRAINT "fk_DIRECCION" FOREIGN KEY ("ID_MUNICIPIO") REFERENCES "MUNICIPIO" ("ID_MUNICIPIO") ON DELETE CASCADE;
ALTER TABLE "DIRECCION" ADD CONSTRAINT "fk_DIRECCION_1" FOREIGN KEY ("ID_COLONIA") REFERENCES "COLONIA" ("ID_COLONIA") ON DELETE SET NULL;
ALTER TABLE "TELEFONO_PERSONA" ADD CONSTRAINT "fk_TELEFONO_PERSONA" FOREIGN KEY ("ID_TELEFONO") REFERENCES "TELEFONO" ("ID_TELEFONO") ON DELETE CASCADE;
ALTER TABLE "TELEFONO_PERSONA" ADD CONSTRAINT "fk_TELEFONO_PERSONA_1" FOREIGN KEY ("ID_PERSONA") REFERENCES "PERSONA" ("ID_PERSONA") ON DELETE CASCADE;
ALTER TABLE "DOCUMENTO" ADD CONSTRAINT "fk_DOCUMENTO" FOREIGN KEY ("ID_TIPO_DOCUMENTO") REFERENCES "TIPO_DOCUMENTO" ("ID_TIPO_DOCUMENTO") ON DELETE CASCADE;
ALTER TABLE "DOCUMENTO_PERSONA" ADD CONSTRAINT "fk_DOCUMENTO_PERSONA" FOREIGN KEY ("ID_DOCUMENTO") REFERENCES "DOCUMENTO" ("ID_DOCUMENTO") ON DELETE CASCADE;
ALTER TABLE "DOCUMENTO_PERSONA" ADD CONSTRAINT "fk_DOCUMENTO_PERSONA_1" FOREIGN KEY ("ID_PERSONA") REFERENCES "PERSONA" ("ID_PERSONA") ON DELETE CASCADE;
ALTER TABLE "TELEFONO" ADD CONSTRAINT "fk_TELEFONO" FOREIGN KEY ("ID_COMPANIA") REFERENCES "COMPANIA_TELEFONO" ("ID_COMPANIA") ON DELETE SET NULL;
ALTER TABLE "TELEFONO" ADD CONSTRAINT "fk_TELEFONO_1" FOREIGN KEY ("ID_TIPO_TELEFONO") REFERENCES "TIPO_TELEFONO" ("ID_TIPO_TELEFONO") ON DELETE SET NULL;
ALTER TABLE "CLIENTE" ADD CONSTRAINT "fk_CLIENTE" FOREIGN KEY ("ID_PERSONA") REFERENCES "PERSONA" ("ID_PERSONA") ON DELETE CASCADE;
ALTER TABLE "PAGO" ADD CONSTRAINT "fk_PAGO" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTE" ("ID_CLIENTE") ON DELETE SET NULL;
ALTER TABLE "CLIENTE" ADD CONSTRAINT "fk_CLIENTE_1" FOREIGN KEY ("ID_ESTADO") REFERENCES "ESTADO" ("ID_ESTADO") ON DELETE SET NULL;
ALTER TABLE "PERSONA" ADD CONSTRAINT "fk_PERSONA" FOREIGN KEY ("ID_ESTADO") REFERENCES "ESTADO" ("ID_ESTADO") ON DELETE SET NULL;
ALTER TABLE "PAGO" ADD CONSTRAINT "fk_PAGO_1" FOREIGN KEY ("ID_TIPO_PAGO") REFERENCES "TIPO_PAGO" ("ID_TIPO_PAGO") ON DELETE SET NULL;

