-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2018-10-21 23:34:35 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE bancos (
    id_banco   INTEGER NOT NULL,
    banco      VARCHAR2(100)
);

ALTER TABLE bancos ADD CONSTRAINT bancos_pk PRIMARY KEY ( id_banco );

CREATE TABLE cita (
    id_cita               INTEGER NOT NULL,
    id_seguro             INTEGER NOT NULL,
    id_persona_paciente   INTEGER NOT NULL,
    cita                  VARCHAR2(30),
    fecha_registro        DATE,
    usuario_registro      VARCHAR2(25),
    fecha_cita            DATE,
    hora_cita             DATE,
    id_clinica            INTEGER NOT NULL
);

ALTER TABLE cita ADD CONSTRAINT cita_pk PRIMARY KEY ( id_cita );

CREATE TABLE cita_persona (
    id_cita      INTEGER NOT NULL,
    id_persona   INTEGER NOT NULL
);

ALTER TABLE cita_persona ADD CONSTRAINT cita_persona_pk PRIMARY KEY ( id_cita,
                                                                      id_persona );

CREATE TABLE clinicas (
    id_clinica    INTEGER NOT NULL,
    id_sede       INTEGER NOT NULL,
    descripcion   VARCHAR2(50)
);

ALTER TABLE clinicas ADD CONSTRAINT clinicas_pk PRIMARY KEY ( id_clinica );

CREATE TABLE colonia (
    id_colonia     INTEGER NOT NULL,
    id_municipio   INTEGER NOT NULL,
    colonia        VARCHAR2(30),
    calle          VARCHAR2(30),
    edificio       VARCHAR2(30)
);

ALTER TABLE colonia ADD CONSTRAINT colonia_pk PRIMARY KEY ( id_colonia );

CREATE TABLE compania_telefono (
    id_compania   INTEGER NOT NULL,
    compania      VARCHAR2(25)
);

ALTER TABLE compania_telefono ADD CONSTRAINT compania_telefono_pk PRIMARY KEY ( id_compania );

CREATE TABLE compras (
    id_compra      INTEGER NOT NULL,
    id_lote        INTEGER,
    id_proveedor   INTEGER,
    no_factura     VARCHAR2(25),
    fecha          DATE,
    recargos       NUMBER,
    descuentos     NUMBER,
    total          NUMBER
);

ALTER TABLE compras ADD CONSTRAINT compras_pk PRIMARY KEY ( id_compra );

CREATE TABLE cuenta_proveedores (
    id_cuenta_prov    INTEGER NOT NULL,
    id_proveedor      INTEGER NOT NULL,
    id_banco_cuenta   INTEGER NOT NULL,
    cuenta            VARCHAR2(50)
);

ALTER TABLE cuenta_proveedores ADD CONSTRAINT cuenta_proveedores_pk PRIMARY KEY ( id_cuenta_prov );

CREATE TABLE cuentas_por_pagar (
    id_cuenta           INTEGER NOT NULL,
    id_proveedor        INTEGER NOT NULL,
    id_compra           INTEGER,
    id_pago_realizado   INTEGER NOT NULL,
    id_status_pago      INTEGER NOT NULL
);

ALTER TABLE cuentas_por_pagar ADD CONSTRAINT cuentas_por_pagar_pk PRIMARY KEY ( id_cuenta );

CREATE TABLE departamento (
    id_departamento   INTEGER NOT NULL,
    id_pais           INTEGER NOT NULL,
    departamento      VARCHAR2(50)
);

ALTER TABLE departamento ADD CONSTRAINT departamento_pk PRIMARY KEY ( id_departamento );

CREATE TABLE detalle_compra (
    id_compra       INTEGER NOT NULL,
    id_producto     INTEGER,
    cantidad        NUMBER,
    precio_unidad   NUMBER,
    total           NUMBER
);

CREATE TABLE detalle_pago (
    id_detalle_pago          INTEGER NOT NULL,
    id_pago                  INTEGER,
    id_compra                INTEGER NOT NULL,
    id_medio_pago            INTEGER,
    id_cuenta_proveedor      INTEGER,
    id_tipo_documento_pago   INTEGER,
    no_doc_pago              NUMBER,
    monto_pago               NUMBER
);

ALTER TABLE detalle_pago ADD CONSTRAINT detalle_pago_pk PRIMARY KEY ( id_detalle_pago );

CREATE TABLE diagnostico (
    id_diagnostico         INTEGER,
    id_persona             INTEGER NOT NULL,
    id_historial_clinico   INTEGER NOT NULL,
    diagnostico            VARCHAR2(100),
    fecha_registro         DATE,
    id_enfermedad          INTEGER NOT NULL
);

CREATE TABLE direccion (
    id_direccion           INTEGER NOT NULL,
    id_zona                INTEGER NOT NULL,
    id_municipio           INTEGER NOT NULL,
    id_departamento        INTEGER NOT NULL,
    id_colonia             VARCHAR2(30),
    referencia_direccion   VARCHAR2(50)
);

ALTER TABLE direccion ADD CONSTRAINT direccion_pk PRIMARY KEY ( id_direccion );

CREATE TABLE direccion_persona (
    id_direccion   INTEGER NOT NULL,
    id_persona     INTEGER NOT NULL
);

ALTER TABLE direccion_persona ADD CONSTRAINT direccion_persona_pk PRIMARY KEY ( id_direccion );

CREATE TABLE direccion_proveedores (
    id_direccion_prov   INTEGER NOT NULL,
    id_proveedor        INTEGER
);

ALTER TABLE direccion_proveedores ADD CONSTRAINT direccion_proveedores_pk PRIMARY KEY ( id_direccion_prov );

CREATE TABLE documento_persona (
    id_tipo_documento   INTEGER NOT NULL,
    id_persona          INTEGER NOT NULL
);

ALTER TABLE documento_persona ADD CONSTRAINT documento_persona_pk PRIMARY KEY ( id_tipo_documento );

CREATE TABLE encargado_sede (
    id_persona          INTEGER NOT NULL,
    id_sede             INTEGER NOT NULL,
    id_encargado_sede   INTEGER
);

ALTER TABLE encargado_sede ADD CONSTRAINT encargado_sede_pk PRIMARY KEY ( id_sede );

CREATE TABLE enfermedad (
    id_enfermedad        INTEGER NOT NULL,
    id_tipo_enfermedad   INTEGER NOT NULL,
    enfermedad           VARCHAR2(50),
    usuario_registro     VARCHAR2(30),
    descripcion          VARCHAR2(500),
    solucion             VARCHAR2(500),
    fecha_registro       DATE
);

ALTER TABLE enfermedad ADD CONSTRAINT enfermedad_pk PRIMARY KEY ( id_enfermedad );

CREATE TABLE especialidad (
    id_especialidad   INTEGER NOT NULL,
    especialidad      VARCHAR2(100)
);

ALTER TABLE especialidad ADD CONSTRAINT especialidad_pk PRIMARY KEY ( id_especialidad );

CREATE TABLE especialidad_medico (
    id_medico         INTEGER NOT NULL,
    id_especialidad   INTEGER NOT NULL,
    fecha_registro    DATE
);

ALTER TABLE especialidad_medico ADD CONSTRAINT especialidad_medico_pk PRIMARY KEY ( id_medico,
                                                                                    id_especialidad );

CREATE TABLE examen_persona (
    id_persona   INTEGER NOT NULL,
    id_examen    INTEGER NOT NULL,
    resultado    VARCHAR2(500)
);

ALTER TABLE examen_persona ADD CONSTRAINT examen_persona_pk PRIMARY KEY ( id_persona,
                                                                          id_examen );

CREATE TABLE examenes (
    id_examen       INTEGER NOT NULL,
    examen          VARCHAR2(100),
    observaciones   VARCHAR2(100)
);

ALTER TABLE examenes ADD CONSTRAINT examenes_pk PRIMARY KEY ( id_examen );

CREATE TABLE historial_clinico (
    id_historial_clinico   INTEGER NOT NULL,
    id_persona             INTEGER NOT NULL,
    via_ingreso            VARCHAR2(50),
    usuario_registro       VARCHAR2(25),
    clinica                VARCHAR2(50),
    observaciones          VARCHAR2(1000),
    fecha_ingreso          DATE,
    altura                 NUMBER(5),
    peso_actual            NUMBER(4),
    peso_anterior          NUMBER(4),
    medida_cintura         NUMBER(5),
    masa_muscular          NUMBER(4),
    presion_arterial       NUMBER(4),
    fecha_registro         DATE
);

ALTER TABLE historial_clinico ADD CONSTRAINT historial_clinico_pk PRIMARY KEY ( id_historial_clinico );

CREATE TABLE insumo (
    id_insumo        INTEGER NOT NULL,
    id_lote          INTEGER,
    nombre           VARCHAR2(100),
    id_laboratorio   INTEGER NOT NULL
);

ALTER TABLE insumo ADD CONSTRAINT insumo_pk PRIMARY KEY ( id_insumo );

CREATE TABLE insumo_clinicas (
    id_clinica   INTEGER NOT NULL,
    id_insumo    INTEGER NOT NULL,
    id_lote      INTEGER NOT NULL,
    cantidad     NUMBER(4)
);

ALTER TABLE insumo_clinicas ADD CONSTRAINT insumo_clinicas_pk PRIMARY KEY ( id_insumo,
                                                                            id_lote );

CREATE TABLE laboratorios_insumos (
    id_laboratorio   INTEGER NOT NULL,
    nombre           VARCHAR2(100)
);

ALTER TABLE laboratorios_insumos ADD CONSTRAINT laboratorios_insumos_pk PRIMARY KEY ( id_laboratorio );

CREATE TABLE lotes (
    id_insumo                   INTEGER NOT NULL,
    id_lote                     INTEGER NOT NULL,
    fecha_vencimiento           DATE,
    insumo_clinicas_id_insumo   INTEGER NOT NULL,
    insumo_clinicas_id_lote     INTEGER NOT NULL
);

ALTER TABLE lotes ADD CONSTRAINT lotes_pk PRIMARY KEY ( id_insumo,
                                                        id_lote );

CREATE TABLE medico (
    id_persona        INTEGER NOT NULL,
    id_medico         INTEGER,
    id_especialidad   INTEGER NOT NULL,
    fecha_ingreso     DATE
);

ALTER TABLE medico ADD CONSTRAINT medico_pk PRIMARY KEY ( id_persona );

CREATE TABLE movimientos_historial (
    id_movimiento_historial   INTEGER NOT NULL,
    id_enfermedad             INTEGER NOT NULL,
    id_examen                 INTEGER NOT NULL,
    id_suspencion             INTEGER,
    fallecimiento             VARCHAR2(50),
    altas                     VARCHAR2(50),
    usuario_registro          VARCHAR2(25),
    fecha_registro            DATE
);

ALTER TABLE movimientos_historial ADD CONSTRAINT movimientos_historial_pk PRIMARY KEY ( id_movimiento_historial );

CREATE TABLE municipios (
    id_municipio      INTEGER NOT NULL,
    id_departamento   INTEGER,
    municipio         VARCHAR2(50)
);

ALTER TABLE municipios ADD CONSTRAINT municipios_pk PRIMARY KEY ( id_municipio );

CREATE TABLE paciente_odontologia (
    id_persona                INTEGER NOT NULL,
    id_paciente_odontologia   INTEGER,
    id_medico                 INTEGER,
    id_clinica                INTEGER NOT NULL
);

CREATE TABLE pago (
    id_pago        INTEGER NOT NULL,
    fecha_pago     DATE,
    id_proveedor   INTEGER NOT NULL
);

ALTER TABLE pago ADD CONSTRAINT pago_pk PRIMARY KEY ( id_pago );

CREATE TABLE pais (
    id_pais   INTEGER NOT NULL,
    pais      VARCHAR2(30)
);

ALTER TABLE pais ADD CONSTRAINT pais_pk PRIMARY KEY ( id_pais );

CREATE TABLE persona (
    id_persona         INTEGER NOT NULL,
    id_telefono        INTEGER,
    id_seguro          INTEGER,
    id_tipo_sangre     INTEGER NOT NULL,
    id_rol             INTEGER NOT NULL,
    primer_nombre      VARCHAR2(30),
    segundo_nombre     VARCHAR2(30),
    primer_apellido    VARCHAR2(30),
    segundo_apellido   VARCHAR2(30),
    apellido_casada    VARCHAR2(30),
    fecha_nacimiento   DATE,
    genero             VARCHAR2(1)
);

ALTER TABLE persona ADD CONSTRAINT persona_pk PRIMARY KEY ( id_persona );

CREATE TABLE proveedores (
    id_proveedor                     INTEGER NOT NULL,
    razon_social                     VARCHAR2(200),
    nit                              VARCHAR2(50),
    representante_legal_id_persona   INTEGER,
    status_proveedor                 INTEGER
);

ALTER TABLE proveedores ADD CONSTRAINT proveedores_pk PRIMARY KEY ( id_proveedor );

CREATE TABLE rol (
    id_rol             INTEGER NOT NULL,
    rol                VARCHAR2(50),
    estado             VARCHAR2(25),
    usuario_registro   VARCHAR2(25),
    fecha_registro     DATE
);

ALTER TABLE rol ADD CONSTRAINT rol_pk PRIMARY KEY ( id_rol );

CREATE TABLE sede (
    id_sede        INTEGER NOT NULL,
    id_direccion   INTEGER,
    nombre         VARCHAR2(100)
);

ALTER TABLE sede ADD CONSTRAINT sede_pk PRIMARY KEY ( id_sede );

CREATE TABLE seguro (
    id_seguro         INTEGER NOT NULL,
    id_tipo_seguro    INTEGER NOT NULL,
    seguro            VARCHAR2(30),
    fecha_registro    DATE,
    vigencia_seguro   DATE
);

ALTER TABLE seguro ADD CONSTRAINT seguro_pk PRIMARY KEY ( id_seguro );

CREATE TABLE status (
    id_status       INTEGER NOT NULL,
    nombre_status   VARCHAR2(50)
);

ALTER TABLE status ADD CONSTRAINT status_pk PRIMARY KEY ( id_status );

CREATE TABLE suspencion_medica (
    id_suspencion        INTEGER NOT NULL,
    id_tipo_suspencion   INTEGER NOT NULL,
    id_persona           INTEGER NOT NULL,
    suspencion           VARCHAR2(50),
    usuario_registro     VARCHAR2(25),
    fecha_registro       DATE,
    motivo               VARCHAR2(500)
);

ALTER TABLE suspencion_medica ADD CONSTRAINT suspencion_medica_pk PRIMARY KEY ( id_suspencion );

CREATE TABLE suspencion_persona (
    id_suspencion   INTEGER NOT NULL,
    id_persona      INTEGER NOT NULL
);

ALTER TABLE suspencion_persona ADD CONSTRAINT suspencion_persona_pk PRIMARY KEY ( id_suspencion );

CREATE TABLE telefono (
    id_telefono        INTEGER NOT NULL,
    id_tipo_telefono   INTEGER,
    id_compania        INTEGER,
    telefono           NUMBER(15)
);

ALTER TABLE telefono ADD CONSTRAINT telefono_pk PRIMARY KEY ( id_telefono );

CREATE TABLE telefono_persona (
    id_telefono   INTEGER NOT NULL,
    id_persona    INTEGER NOT NULL
);

ALTER TABLE telefono_persona ADD CONSTRAINT telefono_persona_pk PRIMARY KEY ( id_telefono );

CREATE TABLE telefono_proveedores (
    id_telefono    INTEGER NOT NULL,
    id_proveedor   INTEGER
);

ALTER TABLE telefono_proveedores ADD CONSTRAINT telefono_proveedores_pk PRIMARY KEY ( id_telefono );

CREATE TABLE tipo_documento (
    id_tipo_documento   INTEGER NOT NULL,
    tipo_documento      VARCHAR2(30)
);

ALTER TABLE tipo_documento ADD CONSTRAINT tipo_documento_pk PRIMARY KEY ( id_tipo_documento );

CREATE TABLE tipo_documentos_pago (
    id_tipo_documento   INTEGER NOT NULL,
    documento           VARCHAR2(50)
);

ALTER TABLE tipo_documentos_pago ADD CONSTRAINT tipo_documentos_pk PRIMARY KEY ( id_tipo_documento );

CREATE TABLE tipo_enfermedad (
    id_tipo_enfermedad   INTEGER NOT NULL,
    tipo_enfermedad      VARCHAR2(50),
    usuario_registro     VARCHAR2(25)
);

ALTER TABLE tipo_enfermedad ADD CONSTRAINT tipo_enfermedad_pk PRIMARY KEY ( id_tipo_enfermedad );

CREATE TABLE tipo_sangre (
    id_tipo_sangre     INTEGER NOT NULL,
    tipo_sangre        VARCHAR2(10),
    usuario_registro   VARCHAR2(25)
);

ALTER TABLE tipo_sangre ADD CONSTRAINT tipo_sangre_pk PRIMARY KEY ( id_tipo_sangre );

CREATE TABLE tipo_seguro (
    id_tipo_seguro   INTEGER NOT NULL,
    tipo_seguro      VARCHAR2(30)
);

ALTER TABLE tipo_seguro ADD CONSTRAINT tipo_seguro_pk PRIMARY KEY ( id_tipo_seguro );

CREATE TABLE tipo_suspencion (
    id_tipo_suspencion   INTEGER NOT NULL,
    tipo_suspencion      VARCHAR2(50)
);

ALTER TABLE tipo_suspencion ADD CONSTRAINT tipo_suspencion_pk PRIMARY KEY ( id_tipo_suspencion );

CREATE TABLE tipo_telefono (
    id_tipo_telefono   INTEGER NOT NULL,
    tipo_telefono      VARCHAR2(50)
);

ALTER TABLE tipo_telefono ADD CONSTRAINT tipo_telefono_pk PRIMARY KEY ( id_tipo_telefono );

CREATE TABLE zonas (
    id_zona            INTEGER NOT NULL,
    id_colonia         INTEGER,
    zona               NUMBER(2),
    fecha_registro     DATE,
    usuario_registro   VARCHAR2(25)
);

ALTER TABLE zonas ADD CONSTRAINT zonas_pk PRIMARY KEY ( id_zona );

ALTER TABLE cita
    ADD CONSTRAINT cita_clinicas_fk FOREIGN KEY ( id_clinica )
        REFERENCES clinicas ( id_clinica );

ALTER TABLE cita
    ADD CONSTRAINT cita_persona_fk FOREIGN KEY ( id_persona_paciente )
        REFERENCES persona ( id_persona );

ALTER TABLE cita
    ADD CONSTRAINT cita_seguro_fk FOREIGN KEY ( id_seguro )
        REFERENCES seguro ( id_seguro );

ALTER TABLE clinicas
    ADD CONSTRAINT clinicas_sede_fk FOREIGN KEY ( id_sede )
        REFERENCES sede ( id_sede );

ALTER TABLE colonia
    ADD CONSTRAINT colonia_municipios_fk FOREIGN KEY ( id_municipio )
        REFERENCES municipios ( id_municipio );

ALTER TABLE compania_telefono
    ADD CONSTRAINT compania_telefono_telefono_fk FOREIGN KEY ( id_compania )
        REFERENCES telefono ( id_telefono );

ALTER TABLE cuenta_proveedores
    ADD CONSTRAINT cuenta_proveedores_bancos_fk FOREIGN KEY ( id_banco_cuenta )
        REFERENCES bancos ( id_banco );

ALTER TABLE cuentas_por_pagar
    ADD CONSTRAINT cuentas_por_pagar_status_fk FOREIGN KEY ( id_status_pago )
        REFERENCES status ( id_status );

ALTER TABLE cuenta_proveedores
    ADD CONSTRAINT cuentayproveedores FOREIGN KEY ( id_proveedor )
        REFERENCES proveedores ( id_proveedor );

ALTER TABLE departamento
    ADD CONSTRAINT departamento_pais_fk FOREIGN KEY ( id_pais )
        REFERENCES pais ( id_pais );

ALTER TABLE detalle_compra
    ADD CONSTRAINT detalle_compra_compras_fk FOREIGN KEY ( id_compra )
        REFERENCES compras ( id_compra );

ALTER TABLE detalle_pago
    ADD CONSTRAINT detalle_pago_compras_fk FOREIGN KEY ( id_compra )
        REFERENCES compras ( id_compra );

ALTER TABLE diagnostico
    ADD CONSTRAINT diagnostico_enfermedad_fk FOREIGN KEY ( id_enfermedad )
        REFERENCES enfermedad ( id_enfermedad );

ALTER TABLE diagnostico
    ADD CONSTRAINT diagnostico_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE diagnostico
    ADD CONSTRAINT diagnosticoehistclinc FOREIGN KEY ( id_historial_clinico )
        REFERENCES historial_clinico ( id_historial_clinico );

ALTER TABLE direccion_proveedores
    ADD CONSTRAINT direcc_provee FOREIGN KEY ( id_direccion_prov )
        REFERENCES direccion ( id_direccion );

ALTER TABLE direccion
    ADD CONSTRAINT direccion_departamento_fk FOREIGN KEY ( id_departamento )
        REFERENCES departamento ( id_departamento );

ALTER TABLE direccion
    ADD CONSTRAINT direccion_direccion_persona_fk FOREIGN KEY ( id_direccion )
        REFERENCES direccion_persona ( id_direccion );

ALTER TABLE direccion
    ADD CONSTRAINT direccion_municipios_fk FOREIGN KEY ( id_municipio )
        REFERENCES municipios ( id_municipio );

ALTER TABLE direccion_persona
    ADD CONSTRAINT direccion_persona_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE direccion
    ADD CONSTRAINT direccion_zonas_fk FOREIGN KEY ( id_zona )
        REFERENCES zonas ( id_zona );

ALTER TABLE documento_persona
    ADD CONSTRAINT documento_persona_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE encargado_sede
    ADD CONSTRAINT encargado_sede_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE encargado_sede
    ADD CONSTRAINT encargado_sede_sede_fk FOREIGN KEY ( id_sede )
        REFERENCES sede ( id_sede );

ALTER TABLE enfermedad
    ADD CONSTRAINT enfermedad_tipo_enfermedad_fk FOREIGN KEY ( id_tipo_enfermedad )
        REFERENCES tipo_enfermedad ( id_tipo_enfermedad );

ALTER TABLE especialidad_medico
    ADD CONSTRAINT especial_medico FOREIGN KEY ( id_medico )
        REFERENCES medico ( id_persona );

ALTER TABLE especialidad_medico
    ADD CONSTRAINT especialidad_especiamd FOREIGN KEY ( id_especialidad )
        REFERENCES especialidad ( id_especialidad );

ALTER TABLE examen_persona
    ADD CONSTRAINT examen_persona_examenes_fk FOREIGN KEY ( id_examen )
        REFERENCES examenes ( id_examen );

ALTER TABLE examen_persona
    ADD CONSTRAINT examen_persona_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE historial_clinico
    ADD CONSTRAINT historial_clinico_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE movimientos_historial
    ADD CONSTRAINT historial_enfer FOREIGN KEY ( id_enfermedad )
        REFERENCES enfermedad ( id_enfermedad );

ALTER TABLE insumo_clinicas
    ADD CONSTRAINT insumo_clinicas_clinicas_fk FOREIGN KEY ( id_clinica )
        REFERENCES clinicas ( id_clinica );

ALTER TABLE insumo_clinicas
    ADD CONSTRAINT insumo_clinicas_insumo_fk FOREIGN KEY ( id_insumo )
        REFERENCES insumo ( id_insumo );

ALTER TABLE insumo
    ADD CONSTRAINT insumo_laboratorios_insumos_fk FOREIGN KEY ( id_laboratorio )
        REFERENCES laboratorios_insumos ( id_laboratorio );

ALTER TABLE lotes
    ADD CONSTRAINT lotes_compras_fk FOREIGN KEY ( id_lote )
        REFERENCES compras ( id_compra );

ALTER TABLE lotes
    ADD CONSTRAINT lotes_insumo_clinicas_fk FOREIGN KEY ( insumo_clinicas_id_insumo,
                                                          insumo_clinicas_id_lote )
        REFERENCES insumo_clinicas ( id_insumo,
                                     id_lote );

ALTER TABLE medico
    ADD CONSTRAINT medico_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE movimientos_historial
    ADD CONSTRAINT movimiento_examenes FOREIGN KEY ( id_examen )
        REFERENCES examenes ( id_examen );

ALTER TABLE paciente_odontologia
    ADD CONSTRAINT odonto_clinicas FOREIGN KEY ( id_clinica )
        REFERENCES clinicas ( id_clinica );

ALTER TABLE paciente_odontologia
    ADD CONSTRAINT odonto_persona FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE pago
    ADD CONSTRAINT pago_detalle_pago_fk FOREIGN KEY ( id_pago )
        REFERENCES detalle_pago ( id_detalle_pago );

ALTER TABLE pago
    ADD CONSTRAINT pago_proveedores_fk FOREIGN KEY ( id_proveedor )
        REFERENCES proveedores ( id_proveedor );

ALTER TABLE persona
    ADD CONSTRAINT persona_rol_fk FOREIGN KEY ( id_rol )
        REFERENCES rol ( id_rol );

ALTER TABLE persona
    ADD CONSTRAINT persona_tipo_sangre_fk FOREIGN KEY ( id_tipo_sangre )
        REFERENCES tipo_sangre ( id_tipo_sangre );

ALTER TABLE cuentas_por_pagar
    ADD CONSTRAINT porpagaryprovee FOREIGN KEY ( id_proveedor )
        REFERENCES proveedores ( id_proveedor );

ALTER TABLE proveedores
    ADD CONSTRAINT prov_direccion FOREIGN KEY ( id_proveedor )
        REFERENCES direccion_proveedores ( id_direccion_prov );

ALTER TABLE proveedores
    ADD CONSTRAINT prov_telefono FOREIGN KEY ( id_proveedor )
        REFERENCES telefono_proveedores ( id_telefono );

ALTER TABLE cuenta_proveedores
    ADD CONSTRAINT relacion_cuentas FOREIGN KEY ( id_cuenta_prov )
        REFERENCES cuentas_por_pagar ( id_cuenta );

ALTER TABLE seguro
    ADD CONSTRAINT seguro_tipo_seguro_fk FOREIGN KEY ( id_tipo_seguro )
        REFERENCES tipo_seguro ( id_tipo_seguro );

ALTER TABLE suspencion_medica
    ADD CONSTRAINT suspen_tiposuspen FOREIGN KEY ( id_tipo_suspencion )
        REFERENCES tipo_suspencion ( id_tipo_suspencion );

ALTER TABLE suspencion_medica
    ADD CONSTRAINT suspencion_medica_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE suspencion_persona
    ADD CONSTRAINT suspencion_persona_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE telefono_persona
    ADD CONSTRAINT telefono_persona_persona_fk FOREIGN KEY ( id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE telefono
    ADD CONSTRAINT telefono_telefono_persona_fk FOREIGN KEY ( id_telefono )
        REFERENCES telefono_persona ( id_telefono );

ALTER TABLE telefono_proveedores
    ADD CONSTRAINT telprov_tel FOREIGN KEY ( id_telefono )
        REFERENCES telefono ( id_telefono );

ALTER TABLE tipo_telefono
    ADD CONSTRAINT tipo_telefono_telefono_fk FOREIGN KEY ( id_tipo_telefono )
        REFERENCES telefono ( id_telefono );

ALTER TABLE tipo_documento
    ADD CONSTRAINT tipodoc_docpersona FOREIGN KEY ( id_tipo_documento )
        REFERENCES documento_persona ( id_tipo_documento );

ALTER TABLE tipo_documentos_pago
    ADD CONSTRAINT tipodocpag_detpago FOREIGN KEY ( id_tipo_documento )
        REFERENCES detalle_pago ( id_detalle_pago );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            53
-- CREATE INDEX                             0
-- ALTER TABLE                            108
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

