CREATE TABLE "PACIENTE_ODONTOLOGIA" (
"ID_PACIENTE_ODONTOLOGIA" NUMERIC(5,0) NOT NULL,
"ID_PACIENTE" NUMERIC(5,0) NOT NULL,
"ID_MEDICO" NUMERIC(5,0) NOT NULL,
"ID_CLINICA" NUMERIC(5,0) NOT NULL,
PRIMARY KEY ("ID_PACIENTE", "ID_MEDICO", "ID_CLINICA", "ID_PACIENTE_ODONTOLOGIA") 
)
NOCOMPRESS 
NOPARALLEL ;

CREATE TABLE "MEDICO" (
"ID_MEDICO" NUMERIC(5,0) NOT NULL,
"ID_PERSONA" NUMBER NOT NULL,
"FECHA_INGRESO" DATE NOT NULL,
PRIMARY KEY ("ID_MEDICO", "ID_PERSONA") 
)
NOCOMPRESS 
NOPARALLEL ;

CREATE TABLE "CLINICA" (
"ID_CLINICA" NUMERIC(5,0) NOT NULL,
"ID_DIRECCION" NUMERIC(5,0) NOT NULL,
"DESCRIPCION" VARCHAR2(2555) NULL,
PRIMARY KEY ("ID_CLINICA", "ID_DIRECCION") 
)
NOCOMPRESS 
NOPARALLEL ;

CREATE TABLE "DIAGNOSTICO" (
"ID_DIAGNOSTICO" NUMERIC(5,0) NOT NULL,
"ID_PACIENTE" NUMERIC(5,0) NOT NULL,
"ID_HISTORIAL_CLINICO" NUMBER NOT NULL,
"DIAGNOSTICO" VARCHAR2(255) NULL,
"FECHA_REGISTRO" DATE NULL,
"ID_ENFERMEDAD" NUMBER NOT NULL,
PRIMARY KEY ("ID_DIAGNOSTICO", "ID_PACIENTE", "ID_HISTORIAL_CLINICO", "ID_ENFERMEDAD") 
)
NOCOMPRESS 
NOPARALLEL ;

CREATE TABLE "ESPECIALIDAD_MEDICO" (
"ID_MEDICO" NUMERIC(5,0) NOT NULL,
"ID_ESPECIALIDAD" NUMBER NOT NULL,
"FECHA_REGISTRO" DATE NULL,
PRIMARY KEY ("ID_MEDICO", "ID_ESPECIALIDAD") 
)
NOCOMPRESS 
NOPARALLEL ;


ALTER TABLE "PACIENTE_ODONTOLOGIA" ADD CONSTRAINT "FK_PACIENTE_ODONTOLOGIA_PACIENTE_ODONTOLOGIA_1" FOREIGN KEY ("ID_CLINICA") REFERENCES "CLINICA" ("ID_CLINICA") ON DELETE CASCADE;
ALTER TABLE "PACIENTE_ODONTOLOGIA" ADD CONSTRAINT "FK_PACIENTE_ODONTOLOGIA_PACIENTE_ODONTOLOGIA_3" FOREIGN KEY ("ID_MEDICO") REFERENCES "MEDICO" ("ID_MEDICO") ON DELETE CASCADE;
ALTER TABLE "ESPECIALIDAD_MEDICO" ADD CONSTRAINT "FK_ESPECIALIDAD_MEDICO_ESPECIALIDAD_MEDICO_1" FOREIGN KEY ("ID_MEDICO") REFERENCES "MEDICO" ("ID_MEDICO") ON DELETE CASCADE;
ALTER TABLE "DIAGNOSTICO" ADD CONSTRAINT "FK_DIAGNOSTICO_DIAGNOSTICO_1" FOREIGN KEY ("ID_PACIENTE") REFERENCES "PACIENTE_ODONTOLOGIA" ("ID_PACIENTE_ODONTOLOGIA") ON DELETE CASCADE;

